services:
  - type: web
    name: national-insurance-company
    runtime: docker
    branch: main
    plan: free
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
